- android/build.gradle
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- ios/Classes/FlutterQrPlugin.m
1. error when xcode 10
2. release camera when widget dispose (maybe fixed #1)
> fix #2 #3 and optimization

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
> Improve and fix bugs

- android/build.gradle
- ios/qr_code_scanner.podspec
- pubspec.yaml
Included swift 5 requirements on the specifications of the project
> included swift 5 in the project's specifications and updated androidX dependency

- README.md
Add instructions for iOS usage.
> Added iOS Instructions

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- example/lib/main.dart
- ios/Classes/QRView.swift
- lib/qr_code_scanner.dart
Added the ability to pause and resume the camera from Flutter.
> Add ability to pause/resume the camera

- README.md
- example/lib/main.dart
- lib/qr_code_scanner.dart
Instead of initializing the controller/iOS dimensions inside the widget, the controller handles the initialization itself. The controller only exposes a stream of data.
Examples adapted accordingly.
> Simplfiy controller, expose scanDataStream

- README.md
For Android people it's not obvious why app crashes.
> Add NSCameraUsageDescription example

- android/build.gradle
- android/src/main/AndroidManifest.xml
- example/android/app/build.gradle
This should fix https://github.com/juliuscanute/qr_code_scanner/issues/90
I changed the minSdk version to 19 but only tested that version on the emulator. I had a device running sdk 23 and the example app worked on that device.
> Changed minSdkVersion to 19

- ios/Classes/QRView.swift
Fixes #113 memory leak which caused not disposing camera from memory.
> [iOS] Fix disposing camera from memory

- ios/Classes/QRView.swift
- ios/Classes/QRViewFactory.swift
This PR is fixing ios compile error with swift 4
> replace var to let

- android/build.gradle
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/Shared.kt
- example/android/app/build.gradle
- example/android/app/src/main/AndroidManifest.xml
- example/android/app/src/main/kotlin/net/touchcapture/qr/flutterqrexample/MainActivity.kt
- example/android/app/src/main/res/values/styles.xml
> 132 embedding v2

- analysis_options.yaml
- example/README.md
- example/lib/main.dart
- example/pubspec.yaml
- ios/Classes/QRView.swift
- lib/src/qr_code_scanner.dart
- pubspec.yaml
See #125 
fixes #34, #87 and #112
> Fixed rotation on iOS.

- example/lib/main.dart
> #76 Fixed screen going black after hot reload.

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- example/lib/main.dart
- ios/Classes/QRView.swift
- lib/src/qr_code_scanner.dart
This currently supports all types present on android. For iOs, only a subset is supported.
This should fix https://github.com/juliuscanute/qr_code_scanner/issues/63.
> Add BarcodeFormat to result

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt
> #181 Fixes activity being null 

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/Shared.kt
> 185 permission on app start

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- example/ios/Runner.xcodeproj/project.pbxproj
- ios/qr_code_scanner.podspec
- lib/src/qr_code_scanner.dart
> 57 raw bytes android

- README.md
`result` should change with each `SetState()` in `_onQRViewCreated(QRViewController controller))`, not `qrText`. 
`qrText` isn't defined!
> Example Code typo fix.

- README.md
- example/README.md
- example/lib/main.dart
I think that is a good idea to update all the docs and sample in order to use async/await method as it is a good practise and way to manage code.
> Update example and README.md with new async methods

- example/ios/Runner.xcodeproj/project.pbxproj
- ios/Classes/QRView.swift
> Fixed scan area not honored

- lib/src/qr_code_scanner.dart
> Updated ShapeBorder to QrScannerOverlayShape

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- ios/Classes/QRView.swift
- lib/src/qr_code_scanner.dart
> Fixed permission callback.

- example/android/gradle.properties
- ios/Classes/QRView.swift
- lib/src/qr_code_scanner.dart
> 235 bottom offset

- lib/src/qr_code_scanner.dart
> Fixed null-pointer when no overlay set on iOS

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- example/lib/main.dart
- ios/Classes/QRView.swift
- lib/src/qr_code_scanner.dart
> 240 green dot ios

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
> Fixed auto resuming while paused on Android

- .gitignore
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/Shared.kt
- ios/Classes/QRView.swift
- lib/src/lifecycle_event_handler.dart
- lib/src/qr_code_scanner.dart
> 252 unknown exception

- lib/src/qr_code_scanner.dart
> Fixed CameraException on Android when disposing (#257)

- lib/src/qr_code_scanner.dart
> Add LifecycleEventHandler to dispose function. (#265)

- android/build.gradle
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/android/settings.gradle
> imp: updated gradle dependencies

- lib/qr_code_scanner.dart
- pubspec.yaml
> Remove web-dependency to enable builds on io platforms

- README.md
Fixed the README for file for Android compatibility. This is based on the issue: https://github.com/juliuscanute/qr_code_scanner/issues/325
> Changed README file for Android compatibility

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/CustomFramingRectBarcodeView.java
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt
- example/lib/main.dart
- lib/src/qr_code_scanner.dart
Added resizing of the scan area on android in accordance with QrScannerOverlayShape
> Correct scan area size on android

- ios/Classes/FlutterQrPlugin.m
> fix invoke issue.

- ios/Classes/QRView.swift
- lib/src/qr_code_scanner.dart
- lib/src/types/barcode.dart
Since I needed it for a project of my own, I added support for bytes in iOS as much as possible. If this is a useful change for the package, I would be happy if it helps other people besides me.
> Added raw-bytes support for iOS

- README.md
Added null checks in the README.md file and a detailed explanation of minimum Android SDK Version to 20.
> Null Check Additions and Detailed explanation to the minSdkVersion

- lib/src/qr_scanner_overlay_shape.dart
Fix assert so that no exception is thrown if the cutOutSize is not specified
> Assert fixed

- lib/src/qr_code_scanner.dart
It is solution work, please approve this pull request because your solution is not work
> fix: fixed padding in shape

- ios/Classes/QRView.swift
> bug: fix crash because of unsupported iOS version

- CHANGELOG.md
- android/build.gradle
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- pubspec.yaml
> Gradle & sdk update, permission fix

- lib/src/qr_scanner_overlay_shape.dart
- lib/src/web/flutter_qr_stub.dart
- lib/src/web/flutter_qr_web.dart
> feat: Migrate to flutter 2.10.1

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt
Fix for the issue https://github.com/juliuscanute/qr_code_scanner/issues/511
> fix: platform break changes

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
Properly fixes issues #488 #220 #367
> Read normal & inverted (white on black) qr codes at same time

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/CustomFramingRectBarcodeView.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QrActivityLifecycleCallbacks.kt
- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QrShared.kt
- Remove usage of double bang operator
Remove usages of double bang `(!!)` operator to avoid `NullPointerException`
- Remove registered callbacks onDispose
Unregister lifecycle listener when View is disposed, so we do not have any leak on Application lifecycle listener.
- Code Refactor
Create code regions, Use of Kotlin extension functions.
- Reduce Magic Strings with Constants
Reduce usage of same string value by replacing with constants
- Remove caching hasCameraPermission
Calling `hasCameraPermission` always will return the current state of permission.
Caching the permission causes issues when coming back to the application, and user manually revoked the permission from Settings.
- Check for camera permission on Activity Resume
Before resuming QR Scanner, check if the app still has …
> Cleanup refactor

- android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
- example/ios/Runner.xcodeproj/project.pbxproj
- example/lib/main.dart
- example/pubspec.yaml
- ios/Classes/QRView.swift
- lib/src/qr_code_scanner.dart
- lib/src/web/flutter_qr_web.dart
Enhancement: https://github.com/juliuscanute/qr_code_scanner/issues/618
- enable android/iOS scan qrcode from gallery
> enhancement: enable scan qrcode from gallery
